{\rtf1\ansi\ansicpg1252\cocoartf2577
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 Description:  Udacity - Design for Availability, Resilience, and Reliability\
    \
Parameters:\
  MasterUserPassword:\
    Description: The password for the Admin user\
    Type: String\
    \
  role:\
    Description: The role of the vpc, primary or secondary\
    Type: String\
    \
  databaseName:\
    Description: The name of the database\
    Type: String\
    \
  databaseInstanceName:\
    Description: The instance name of the  database\
    Type: String\
    \
Resources:\
\
  RDSDBSubnetGroup:\
    Type: "AWS::RDS::DBSubnetGroup"\
    Properties:\
        DBSubnetGroupDescription: "Subnet Group for primary mySQL database"\
        DBSubnetGroupName: !Sub "$\{role\}-database-subnet-group"\
        SubnetIds: \
          - Fn::ImportValue: !Sub "$\{role\}-PrivateSubnet1"\
          - Fn::ImportValue: !Sub "$\{role\}-PrivateSubnet2"\
        Tags: \
          - Key: Name\
            Value: !Sub "$\{role\}-database-subnet-group"\
\
  RDSDBInstance:\
      Type: AWS::RDS::DBInstance\
      Properties:\
          DBInstanceIdentifier: !Ref databaseInstanceName\
          AllocatedStorage: 20\
          DBInstanceClass: db.t2.micro\
          Engine: "MYSQL"\
          MasterUsername: Admin\
          MasterUserPassword: !Ref MasterUserPassword\
          BackupRetentionPeriod: 7\
          MultiAZ: false\
          EngineVersion: 8.0.20\
          AutoMinorVersionUpgrade: true\
          PubliclyAccessible: false\
          Port: 3306\
          CopyTagsToSnapshot: true\
          DeletionProtection: false\
          DBSubnetGroupName: !Ref RDSDBSubnetGroup\
          VPCSecurityGroups: \
            - Fn::ImportValue: !Sub $\{role\}-DatabaseSecurityGroup\
          StorageType: gp2\
          MaxAllocatedStorage: 1000\
          DBName: !Ref databaseName\
          Tags: \
            - Key: Name\
              Value: !Sub "$\{role\}-database-subnet-group"\
        \
Outputs:\
  dbSubnetGroup:\
    Description: the subnet group for the rds database\
    Value: !Ref RDSDBSubnetGroup\
    Export: \
      Name: !Sub $\{role\}-dbSubnetGroup\
      \
      \
  dbInstance:\
    Description: The id for the db\
    Value: !Ref RDSDBInstance\
    Export: \
      Name: !Sub $\{role\}-dbInstance}