Description:  Udacity - Design for Availability, Resilience, and Reliability
    
Parameters:
  MasterUserPassword:
    Description: The password for the Admin user
    Type: String
    
  role:
    Description: The role of the vpc, primary or secondary
    Type: String
    
  databaseName:
    Description: The name of the database
    Type: String
    
  databaseInstanceName:
    Description: The instance name of the  database
    Type: String
    
Resources:

  RDSDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
        DBSubnetGroupDescription: "Subnet Group for primary mySQL database"
        DBSubnetGroupName: !Sub "${role}-database-subnet-group"
        SubnetIds: 
          - Fn::ImportValue: !Sub "${role}-PrivateSubnet1"
          - Fn::ImportValue: !Sub "${role}-PrivateSubnet2"
        Tags: 
          - Key: Name
            Value: !Sub "${role}-database-subnet-group"

  RDSDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
          DBInstanceIdentifier: !Ref databaseInstanceName
          AllocatedStorage: 20
          DBInstanceClass: db.t2.micro
          Engine: "MYSQL"
          MasterUsername: Admin
          MasterUserPassword: !Ref MasterUserPassword
          BackupRetentionPeriod: 7
          MultiAZ: false
          EngineVersion: 8.0.20
          AutoMinorVersionUpgrade: true
          PubliclyAccessible: false
          Port: 3306
          CopyTagsToSnapshot: true
          DeletionProtection: false
          DBSubnetGroupName: !Ref RDSDBSubnetGroup
          VPCSecurityGroups: 
            - Fn::ImportValue: !Sub ${role}-DatabaseSecurityGroup
          StorageType: gp2
          MaxAllocatedStorage: 1000
          DBName: !Ref databaseName
          Tags: 
            - Key: Name
              Value: !Sub "${role}-database-subnet-group"
        
Outputs:
  dbSubnetGroup:
    Description: the subnet group for the rds database
    Value: !Ref RDSDBSubnetGroup
    Export: 
      Name: !Sub ${role}-dbSubnetGroup
      
      
  dbInstance:
    Description: The id for the db
    Value: !Ref RDSDBInstance
    Export: 
      Name: !Sub ${role}-dbInstance
